### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Soumi7** [NetoPedro/Deep-Learning-Push-Up-Counter#3]
Could you share the dataset without the preprocessing?

**Comment by NetoPedro** [comment]
Sorry for the delayed answer. Unfortunately, the dataset without preprocessing contains private and sensitive information. Hence, I am not able to share it directly. However, I can share how it was collected. The main task required finding videos of people doing push-ups. After separating all the frames, they were labelled as going up, down or neither. Please, reopen this issue if you have more questions.
